// <auto-generated />
using System;
using BOTW.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BOTW.Migrations
{
    [DbContext(typeof(BOTWContext))]
    [Migration("20210107192737_StyleOwned")]
    partial class StyleOwned
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BOTW.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("BOTW.Models.CharacterLocationStyle", b =>
                {
                    b.Property<int>("CharacterLocationStyleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CharacterId");

                    b.Property<int?>("LocationId");

                    b.Property<int?>("StyleId");

                    b.HasKey("CharacterLocationStyleId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("LocationId");

                    b.HasIndex("StyleId");

                    b.ToTable("CharacterLocationStyle");
                });

            modelBuilder.Entity("BOTW.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("BOTW.Models.Style", b =>
                {
                    b.Property<int>("StyleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<bool>("Owned");

                    b.HasKey("StyleId");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("BOTW.Models.CharacterLocationStyle", b =>
                {
                    b.HasOne("BOTW.Models.Character", "Character")
                        .WithMany("JoinEntries")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BOTW.Models.Location", "Location")
                        .WithMany("JoinEntries")
                        .HasForeignKey("LocationId");

                    b.HasOne("BOTW.Models.Style", "Style")
                        .WithMany("JoinEntries")
                        .HasForeignKey("StyleId");
                });
#pragma warning restore 612, 618
        }
    }
}
